<h1>Python: without numpy or sklearn </h1>

<h3> Q1: Given two matrices please print the product of those two matrices </h3>
<pre>

Ex 1: A   = [[1 3 4]
             [2 5 7]
             [5 9 6]]
      B   = [[1 0 0]
             [0 1 0]
             [0 0 1]]
      A*B = [[1 3 4]
             [2 5 7]
             [5 9 6]]

     
Ex 2: A   = [[1 2]
             [3 4]]
      B   = [[1 2 3 4 5]
             [5 6 7 8 9]]
      A*B = [[11 14 17 20 23]
             [23 30 36 42 51]]
             
Ex 3: A   = [[1 2]
             [3 4]]
      B   = [[1 4]
             [5 6]
             [7 8]
             [9 6]]
      A*B =Not possible
</pre>

In [1]:
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples


# you can free to change all these codes/structure
# here A and B are list of lists


def matrix_mul(a, b):
    mm = []
    for i in range(len(a)):
        temp = []   # It will save new row
        for j in range(len(b[0])):
            s = 0   # s: sum
            for _ in range(len(b)):
                s += int(a[i][_]) * int(b[_][j])
            temp.append(s)
        mm.append(temp)
    return mm


A = [[1, 2],
     [3, 4]]

B = [[1, 2, 3, 4, 5],
     [5, 6, 7, 8, 9]]

if len(A[0]) == len(B):
    print(matrix_mul(A, B))
else:
    print("Not possible")


[[11, 14, 17, 20, 23], [23, 30, 37, 44, 51]]


<h3> Q2: Select a number randomly with probability proportional to its magnitude from the given array of n elements</h3>

consider an experiment, selecting an element from the list A randomly with probability proportional to its magnitude.
assume we are doing the same experiment for 100 times with replacement, in each experiment you will print a number that is selected randomly from A.

<pre>
Ex 1: A = [0 5 27 6 13 28 100 45 10 79]
let f(x) denote the number of times x getting selected in 100 experiments.
f(100) > f(79) > f(45) > f(28) > f(27) > f(13) > f(10) > f(6) > f(5) > f(0)
</pre>

In [2]:
import random


def pick_a_number_from_list(A):
    # your code here for picking an element from with the probability proportional to its magnitude
    s = sum(A)
    d_dash = list()
    for i in A:
        d_dash.append(i/s)

    d_bar = list()  # for cumulative sum
    d_bar.append(0)
    for j in range(len(A)):
        d_bar.append(d_bar[j] + d_dash[j])

    r = random.uniform(0.0, 1.0)
    number = 0

    for k in range(1, len(d_bar)):
        if r <= d_bar[k]:
            number = A[k-1]
            return number


def sampling_based_on_magnitued():
    for i in range(1, 100):
        number = pick_a_number_from_list(A)
        print(number)


A = [0, 5, 27, 6, 13, 28, 100, 45, 10, 79]
# A = [2.0, 6.0, 1.2, 5.8, 20.0]
sampling_based_on_magnitued()


27
100
100
100
45
45
100
13
28
5
28
27
100
45
100
79
100
100
45
79
28
100
79
100
100
100
100
100
100
100
79
45
28
100
100
100
79
79
100
79
45
79
45
100
79
45
45
79
100
79
100
79
28
100
6
45
27
28
45
45
79
79
28
45
79
45
79
100
100
100
79
45
13
100
79
10
100
79
45
79
100
100
28
45
100
10
28
45
79
27
100
45
100
10
45
27
79
100
100


<h3> Q3: Replace the digits in the string with #</h3>

consider a string that will have digits in that, we need to remove all the not digits and replace the digits with #
<pre>
Ex 1: A = 234                Output: ###
Ex 2: A = a2b3c4             Output: ###
Ex 3: A = abc                Output:   (empty string)
Ex 5: A = #2a$#b%c%561#      Output: ####
</pre>

In [3]:
import re
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples

# you can free to change all these codes/structure
# String: it will be the input to your program


def replace_digits(s):
    x = re.sub(r'\D', '', s)
    x = re.sub(r'\d', '#', x)
    return x    # modified string which is after replacing the # with digits


string1 = '234'
string2 = 'a2b3c4'
string3 = 'abc'
string4 = '#2a$#b%c%561#'

print(replace_digits(string1))
print(replace_digits(string2))
print(replace_digits(string3))
print(replace_digits(string4))


###
###

####


<h3> Q4: Students marks dashboard</h3>

consider the marks list of class students given two lists <br>
Students = ['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] <br>
Marks = [45, 78, 12, 14, 48, 43, 45, 98, 35, 80] <br>
from the above two lists the Student[0] got Marks[0],  Student[1] got Marks[1] and so on <br><br>
your task is to print the name of students
<strong>a. Who got top 5 ranks, in the descending order of marks</strong> <br>
<strong>b. Who got least 5 ranks, in the increasing order of marks</strong><br>
<strong>d. Who got marks between  &gt;25th percentile &lt;75th percentile, in the increasing order of marks</strong>

<pre>
Ex 1: 
Students=['student1','student2','student3','student4','student5','student6','student7','student8','student9','student10'] 
Marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]
a. 
student8  98
student10 80
student2  78
student5  48
student7  47
b.
student3 12
student4 14
student9 35
student6 43
student1 45
c.
student9 35
student6 43
student1 45
student7 47
student5 48
</pre>

In [4]:
import math


def display_dash_board(students, marks):
    students_marks_zipped_list = list(zip(students, marks))
    students_marks_zipped_list = sorted(students_marks_zipped_list, key=lambda x: x[1])    # x[1]: Marks

    # write code for computing top 5 students
    top_5_students = students_marks_zipped_list[-5:]

    # write code for computing least 5 students
    least_5_students = students_marks_zipped_list[:5]

    length = len(students_marks_zipped_list)
    a = math.floor(0.25 * length)
    b = math.floor(0.75 * length)
    students_within_25_and_75 = students_marks_zipped_list[a:b]

    return top_5_students, least_5_students, students_within_25_and_75


if __name__ == '__main__':
    students = ['student1', 'student2', 'student3', 'student4', 'student5', 'student6', 'student7', 'student8',
                'student9', 'student10']
    marks = [45, 78, 12, 14, 48, 43, 47, 98, 35, 80]

    if len(students) > 5 and len(marks) > 5:
        top_5_students, least_5_students, students_within_25_and_75 = display_dash_board(students, marks)

    for i in range(4, -1, -1):
        print("{} {}".format(top_5_students[i][0], top_5_students[i][1]))

    print("-"*20)

    for ele in least_5_students:
        print("{} {}".format(ele[0], ele[1]))

    print("-"*20)

    for ele in students_within_25_and_75:
        print("{} {}".format(ele[0], ele[1]))


student8 98
student10 80
student2 78
student5 48
student7 47
--------------------
student3 12
student4 14
student9 35
student6 43
student1 45
--------------------
student9 35
student6 43
student1 45
student7 47
student5 48


<h3> Q5: Find the closest points</h3>

consider you have given n data points in the form of list of tuples like S=[(x1,y1),(x2,y2),(x3,y3),(x4,y4),(x5,y5),..,(xn,yn)] and a point P=(p,q) <br> your task is to find 5 closest points(based on cosine distance) in S from P
<br>cosine distance between two points (x,y) and (p,q) is defind as $cos^{-1}(\frac{(x\cdot p+y\cdot q)}{\sqrt(x^2+y^2)\cdot\sqrt(p^2+q^2)})$
<pre>
Ex:

S= [(1,2),(3,4),(-1,1),(6,-7),(0, 6),(-5,-8),(-1,-1)(6,0),(1,-1)]
P= (3,-4)
<img src='https://i.imgur.com/vIFPOcG.jpg', width=300>
Output:
(6,-7)
(1,-1)
(6,0)
(-5,-8)
(-1,-1)
</pre>

In [5]:
import math

# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input examples
# you can free to change all these codes/structure


# here S is list of tuples and P is a tuple ot len=2
def closest_points_to_p(S, P):
    list_of_closest_points = list()  # write your code here
    closest_points = list()

    for point in S:
        cos_x_y_numerator = point[0] * P[0] + point[1] * P[1]
        cos_x_y_denominator = math.sqrt(point[0]**2 + point[1]**2) * math.sqrt(P[0]**2 + P[1]**2)

        if cos_x_y_denominator != 0:
            cosine_distance = math.acos(cos_x_y_numerator / cos_x_y_denominator)
            list_of_closest_points.append((cosine_distance, point))

    list_of_closest_points = sorted(list_of_closest_points, key=lambda x: x[0])
    for i in range(5):
        closest_points.append(list_of_closest_points[i][1])

    return closest_points  # its list of tuples


if __name__ == '__main__':
    S = [(1, 2), (3, 4), (-1, 1), (6, -7), (0, 6), (-5, -8), (-1, -1), (6, 0), (1, -1)]
    P = (3, -4)
    points = closest_points_to_p(S, P)
    for p in points:
        print(p)   # print the returned values


(6, -7)
(1, -1)
(6, 0)
(-5, -8)
(-1, -1)


<h3> Q6: Find Which line separates oranges and apples</h3>
consider you have given two set of data points in the form of list of tuples like 
<pre>
Red =[(R11,R12),(R21,R22),(R31,R32),(R41,R42),(R51,R52),..,(Rn1,Rn2)]
Blue=[(B11,B12),(B21,B22),(B31,B32),(B41,B42),(B51,B52),..,(Bm1,Bm2)]
</pre>
and set of line equations(in the string formate, i.e list of strings)
<pre>
Lines = [a1x+b1y+c1,a2x+b2y+c2,a3x+b3y+c3,a4x+b4y+c4,..,K lines]
Note: you need to string parsing here and get the coefficients of x,y and intercept
</pre>
your task is to for each line that is given print "YES"/"NO", you will print yes, if all the red points are one side of the line and blue points are other side of the line, otherwise no
<pre>
Ex:
Red= [(1,1),(2,1),(4,2),(2,4), (-1,4)]
Blue= [(-2,-1),(-1,-2),(-3,-2),(-3,-1),(1,-3)]
Lines=["1x+1y+0","1x-1y+0","1x+0y-3","0x+1y-0.5"]
<img src='https://i.imgur.com/DoQf7mE.jpg' width=400>
Output:
YES
NO
NO
YES
</pre>

In [6]:
def i_am_the_one(red, blue, line):
    eq = line.replace('x', '*{}'.format(red[0][0])).replace('y', '*{}'.format(red[0][1]))
    sign = 1
    if eval(eq) < 0:
        sign = -1

    for point in red:
        eqn = line.replace('x', '*{}'.format(point[0])).replace('y', '*{}'.format(point[1]))
        if sign == 1 and eval(eqn) < 0:
            return 'NO'
        if sign == -1 and eval(eqn) > 0:
            return 'NO'

    sign_for_blue_points = -sign

    for point in blue:
        eqn = line.replace('x', '*{}'.format(point[0])).replace('y', '*{}'.format(point[1]))
        if sign_for_blue_points == 1 and eval(eqn) < 0:
            return 'NO'
        if sign_for_blue_points == -1 and eval(eqn) > 0:
            return 'NO'

    return 'YES'    # yes/no


if __name__ == '__main__':
    Red = [(1, 1), (2, 1), (4, 2), (2, 4), (-1, 4)]
    Blue = [(-2, -1), (-1, -2), (-3, -2), (-3, -1), (1, -3)]
    Lines = ["1x+1y+0", "1x-1y+0", "1x+0y-3", "0x+1y-0.5"]

    for i in Lines:
        yes_or_no = i_am_the_one(Red, Blue, i)
        print(yes_or_no)  # the returned value


YES
NO
NO
YES


<h3> Q7: Filling the missing values in the specified formate</h3>
You will be given a string with digits and '\_'(missing value) symbols you have to replace the '\_' symbols as explained 
<pre>
Ex 1: _, _, _, 24 ==> 24/4, 24/4, 24/4, 24/4 i.e we. have distributed the 24 equally to all 4 places <br>
Ex 2: 40, _, _, _, 60 ==> (60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5,(60+40)/5 ==> 20, 20, 20, 20, 20 i.e. the sum of (60+40) is distributed qually to all 5 places<br>
Ex 3: 80, _, _, _, _  ==> 80/5,80/5,80/5,80/5,80/5 ==> 16, 16, 16, 16, 16 i.e. the 80 is distributed qually to all 5 missing values that are right to it<br>
Ex 4: _, _, 30, _, _, _, 50, _, _  
==> we will fill the missing values from left to right 
    a. first we will distribute the 30 to left two missing values (10, 10, 10, _, _, _, 50, _, _)
    b. now distribute the sum (10+50) missing values in between (10, 10, 12, 12, 12, 12, 12, _, _) 
    c. now we will distribute 12 to right side missing values (10, 10, 12, 12, 12, 12, 4, 4, 4)
</pre>
for a given string with comma seprate values, which will have both missing values numbers like ex: "_, _, x, _, _, _"
you need fill the missing values

Q: your program reads a string like ex: "_, _, x, _, _, _" and returns the filled sequence

Ex: 
<pre>
Input1: "_,_,_,24"
Output1: 6,6,6,6

Input2: "40,_,_,_,60"
Output2: 20,20,20,20,20

Input3: "80,_,_,_,_"
Output3: 16,16,16,16,16

Input4: "_,_,30,_,_,_,50,_,_"
Output4: 10,10,12,12,12,12,4,4,4
</pre>



In [7]:
def curve_smoothing(string):
    new_string = string.split(',')
    length_of_string = len(new_string)
    index_of_numbers_in_list = list()

    for i in range(length_of_string):
        if new_string[i] != '_':
            index_of_numbers_in_list.append(i)

    # if len(index_of_numbers_in_list) == 1 and string[0] != '_':
    index_of_numbers_in_list.append(length_of_string - 1)

    starting_point = 0

    for n in index_of_numbers_in_list:
        if new_string[n] != '_':
            sum_pre_post = int(new_string[n])
        else:
            sum_pre_post = 0

        if new_string[starting_point] != '_' and starting_point != n:
            sum_pre_post += int(new_string[starting_point])
        else:
            sum_pre_post += 0

        replace_with = sum_pre_post // (n - starting_point + 1)

        for j in range(length_of_string):
            if starting_point <= j <= n:
                new_string[j] = replace_with

        starting_point = n

    return new_string


S1 = "_,_,_,24"     # Output1: 6,6,6,6

S2 = "40,_,_,_,60"  # Output2: 20,20,20,20,20

S3 = "80,_,_,_,_"   # Output3: 16,16,16,16,16

S4 = "_,_,30,_,_,_,50,_,_"  # Output4: 10,10,12,12,12,12,4,4,4
smoothed_values = curve_smoothing(S1)
print(smoothed_values)

smoothed_values = curve_smoothing(S2)
print(smoothed_values)

smoothed_values = curve_smoothing(S3)
print(smoothed_values)

smoothed_values = curve_smoothing(S4)
print(smoothed_values)


[6, 6, 6, 6]
[20, 20, 20, 20, 20]
[16, 16, 16, 16, 16]
[10, 10, 12, 12, 12, 12, 4, 4, 4]


<h3> Q8: Filling the missing values in the specified formate</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns
1. the first column F will contain only 5 uniques values (F1, F2, F3, F4, F5)
2. the second column S will contain only 3 uniques values (S1, S2, S3)
<pre>
your task is to find
a. Probability of P(F=F1|S==S1), P(F=F1|S==S2), P(F=F1|S==S3)
b. Probability of P(F=F2|S==S1), P(F=F2|S==S2), P(F=F2|S==S3)
c. Probability of P(F=F3|S==S1), P(F=F3|S==S2), P(F=F3|S==S3)
d. Probability of P(F=F4|S==S1), P(F=F4|S==S2), P(F=F4|S==S3)
e. Probability of P(F=F5|S==S1), P(F=F5|S==S2), P(F=F5|S==S3)
</pre>
Ex:

<pre>
[[F1,S1],[F2,S2],[F3,S3],[F1,S2],[F2,S3],[F3,S2],[F2,S1],[F4,S1],[F4,S3],[F5,S1]]

a. P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
b. P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
c. P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
d. P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
e. P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3
</pre>




In [8]:
def compute_conditional_probabilites(list_A):
    s1 = s2 = s3 = 0
    f11 = f12 = f13 = 0
    f21 = f22 = f23 = 0
    f31 = f32 = f33 = 0
    f41 = f42 = f43 = 0
    f51 = f52 = f53 = 0

    for ele in list_A:
        if 'S1' in ele:
            s1 += 1
        elif 'S2' in ele:
            s2 += 1
        elif 'S3' in ele:
            s3 += 1

    for ele in list_A:
        if ele[0] == 'F1':
            if ele[1] == 'S1':
                f11 += 1
            elif ele[1] == 'S2':
                f12 += 1
            elif ele[1] == 'S3':
                f13 += 1

    print("P(F=F1|S==S1)={}/{}, P(F=F1|S==S2)={}/{}, P(F=F1|S==S3)={}/{}".format(f11, s1, f12, s2, f13, s3))

    for ele in list_A:
        if ele[0] == 'F2':
            if ele[1] == 'S1':
                f21 += 1
            elif ele[1] == 'S2':
                f22 += 1
            elif ele[1] == 'S3':
                f23 += 1

    print("P(F=F2|S==S1)={}/{}, P(F=F2|S==S2)={}/{}, P(F=F2|S==S3)={}/{}".format(f21, s1, f22, s2, f23, s3))

    for ele in list_A:
        if ele[0] == 'F3':
            if ele[1] == 'S1':
                f31 += 1
            elif ele[1] == 'S2':
                f32 += 1
            elif ele[1] == 'S3':
                f33 += 1

    print("P(F=F3|S==S1)={}/{}, P(F=F3|S==S2)={}/{}, P(F=F3|S==S3)={}/{}".format(f31, s1, f32, s2, f33, s3))

    for ele in list_A:
        if ele[0] == 'F4':
            if ele[1] == 'S1':
                f41 += 1
            elif ele[1] == 'S2':
                f42 += 1
            elif ele[1] == 'S3':
                f43 += 1

    print("P(F=F4|S==S1)={}/{}, P(F=F4|S==S2)={}/{}, P(F=F4|S==S3)={}/{}".format(f41, s1, f42, s2, f43, s3))

    for ele in list_A:
        if ele[0] == 'F5':
            if ele[1] == 'S1':
                f51 += 1
            elif ele[1] == 'S2':
                f52 += 1
            elif ele[1] == 'S3':
                f53 += 1

    print("P(F=F5|S==S1)={}/{}, P(F=F5|S==S2)={}/{}, P(F=F5|S==S3)={}/{}".format(f51, s1, f52, s2, f53, s3))


if __name__ == '__main__':
    A = [['F1', 'S1'], ['F2', 'S2'], ['F3', 'S3'], ['F1', 'S2'], ['F2', 'S3'], ['F3', 'S2'], ['F2', 'S1'], ['F4', 'S1'],
         ['F4', 'S3'], ['F5', 'S1']]

    compute_conditional_probabilites(A)


P(F=F1|S==S1)=1/4, P(F=F1|S==S2)=1/3, P(F=F1|S==S3)=0/3
P(F=F2|S==S1)=1/4, P(F=F2|S==S2)=1/3, P(F=F2|S==S3)=1/3
P(F=F3|S==S1)=0/4, P(F=F3|S==S2)=1/3, P(F=F3|S==S3)=1/3
P(F=F4|S==S1)=1/4, P(F=F4|S==S2)=0/3, P(F=F4|S==S3)=1/3
P(F=F5|S==S1)=1/4, P(F=F5|S==S2)=0/3, P(F=F5|S==S3)=0/3


<h3> Q9: Given two sentances S1, S2</h3>
You will be given two sentances S1, S2 your task is to find 
<pre>
a. Number of common words between S1, S2
b. Words in S1 but not in S2
c. Words in S2 but not in S1
</pre>

Ex: 
<pre>
S1= "the first column F will contain only 5 uniques values"
S2= "the second column S will contain only 3 uniques values"
Output:
a. 7
b. ['first','F','5']
c. ['second','S','3']
</pre>

In [9]:
def string_features(S1, S2):
    a = 0
    b = []
    c = []

    txt1 = S1.split(' ')
    txt2 = S2.split(' ')
    for ele in txt1:
        if ele in txt2:
            a += 1

    for ele in txt1:
        if ele not in txt2:
            b.append(ele)

    for ele in txt2:
        if ele not in txt1:
            c.append(ele)

    return a, b, c


S1 = "the first column F will contain only 5 uniques values"
S2 = "the second column S will contain only 3 uniques values"
a, b, c = string_features(S1, S2)
print(a, b, c, sep='\n')


7
['first', 'F', '5']
['second', 'S', '3']


<h3> Q10: Given two sentances S1, S2</h3>
You will be given a list of lists, each sublist will be of length 2 i.e. [[x,y],[p,q],[l,m]..[r,s]]
consider its like a martrix of n rows and two columns

a. the first column Y will contain interger values <br>
b. the second column $Y_{score}$ will be having float values <br>
Your task is to find the value of $f(Y,Y_{score}) = -1*\frac{1}{n}\Sigma_{for each Y,Y_{score} pair}(Ylog10(Y_{score})+(1-Y)log10(1-Y_{score}))$ here n is the number of rows in the matrix
<pre>
Ex:
[[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
output:
0.4243099
</pre>
$\frac{-1}{8}\cdot((1\cdot log_{10}(0.4)+0\cdot log_{10}(0.6))+(0\cdot log_{10}(0.5)+1\cdot log_{10}(0.5)) + ... + (1\cdot log_{10}(0.8)+0\cdot log_{10}(0.2)) )$

In [10]:
from math import log
# write your python code here
# you can take the above example as sample input for your program to test
# it should work for any general input try not to hard code for only given input strings


# you can free to change all these codes/structure
def compute_log_loss(A):
    len_A = len(A)
    ce = 0    # ce: Cross Entropy
    for row in A:
        ce += (row[0] * log(row[1], 10) + ((1 - row[0]) * log(1 - row[1], 10)))
        loss = -1 * ce / len(A)
    # value = -1 / ce * len_A
    return loss


A = [[1, 0.4], [0, 0.5], [0, 0.9], [0, 0.3], [0, 0.6], [1, 0.1], [1, 0.9], [1, 0.8]]
loss = compute_log_loss(A)
print(round(loss, 7))


0.4243099
